# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: repent.proto for package 'repent'

require 'grpc'
require 'repent_pb'

module Repent
  module ChatRoom
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'repent.ChatRoom'

      rpc :Join, ::Repent::JoinRequest, stream(::Repent::Message)
      rpc :Say, ::Repent::MessageContent, ::Repent::Empty
    end

    Stub = Service.rpc_stub_class
  end
end
